project_id = "cjhmbqmhfbspgirnkjkm"

[functions.extract-document-info]
verify_jwt = true

[functions.count-medicine-boxes]
verify_jwt = true

[functions.validate-invoice-xml]
verify_jwt = true

[functions.delete-user]
verify_jwt = true