project_id = "cjhmbqmhfbspgirnkjkm"

[functions.change-user-password]
verify_jwt = true

[functions.extract-document-info]
verify_jwt = true

[functions.count-medicine-boxes]
verify_jwt = true

[functions.validate-invoice-xml]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.extract-payment-proof-info]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.notify-supplier]
verify_jwt = true

[functions.notify-admin]
verify_jwt = true

[functions.export-database-schema]
verify_jwt = true

[functions.export-database-full]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.split-payment]
verify_jwt = true

[functions.validate-payment-complement]
verify_jwt = true

[functions.create-supplier-contador]
verify_jwt = true

[functions.delete-supplier-contador]
verify_jwt = true

[functions.check-smtp-status]
verify_jwt = true

[functions.get-external-medications]
verify_jwt = true

[functions.get-external-purchase-orders]
verify_jwt = true

[functions.send-recovery-email]
verify_jwt = false

[functions.generate-recovery-link]
verify_jwt = true
